In [1]:
%matplotlib qt
import matplotlib.pyplot as plt
import vTEM as vtem
import numpy as np
from math import sqrt, sin, pi

In [4]:
start = vtem.RayNode((15, 15), name='start')
end = vtem.RayNode((15, 0), name = 'end')
initial_ray = vtem.Ray(start, end, name='Initial')
CL1 = vtem.Lens(10, 2, x=0, name='CL1')
CL2 = vtem.Lens(5, 3, x = 0, name='CL2')
CM = vtem.Lens(2, 5, x=-5, name ='CM')
lenses = [CL1, CL2, CM]
rays = [initial_ray]
for n, lens in enumerate(lenses):
    ray = rays[n]
    transmitted_ray = lens(ray)
    transmitted_ray.name = 'Transmitted ({lens.name})'.format(lens=lens)
    print(ray, transmitted_ray)
    rays.append(transmitted_ray)

fig = plt.figure()
ax = fig.add_subplot()
for ray in rays:
    ray.show(ax, 'r.', alpha=0.8, arrowprops={'color':'r', 'alpha': 0.1})
for lens in lenses:
    lens.size=120
    lens.show(ax, lensprops={'ffp':{'linestyle':':', 'color': 'k', 'alpha': 0.1}})

Ray "Initial": (15.00, 15.00) -> (15.00, 10.00) (0.00 deg) Ray "Transmitted (CL1)": (15.00, 10.00) -> (-0.00, 8.00) (-82.41 deg)
Ray "Transmitted (CL1)": (15.00, 10.00) -> (-22.50, 5.00) (-82.41 deg) Ray "Transmitted (CL2)": (-22.50, 5.00) -> (-22.50, 2.00) (0.00 deg)
Ray "Transmitted (CL2)": (-22.50, 5.00) -> (-22.50, 2.00) (0.00 deg) Ray "Transmitted (CM)": (-22.50, 2.00) -> (-5.00, -3.00) (74.05 deg)


In [22]:
start = vtem.RayNode((15, 15), name='start')
end = vtem.RayNode((0, 0), name = 'end')
ray = vtem.Ray(start, end)
print(ray)
ray.extend(10)
print(ray)

Ray "": (15.00, 15.00) -> (0.00, 0.00) (-45.00 deg)
Ray "": (15.00, 15.00) -> (10.00, 10.00) (-45.00 deg)


In [2]:
start = vtem.RayNode((0., 0.), name='start')
end = vtem.RayNode((10., -9.), name = 'end')
ray = vtem.Ray(start, end)

print(start)
print(end)
print(ray)

fig = plt.figure()
ax = fig.add_subplot()
ray.show(ax, 'r')

RayNode " (start)": (0.00, 0.00)
RayNode " (end)": (10.00, -9.00)
Ray "": (0.00, 0.00) -> (10.00, -9.00) (48.01 deg)


In [6]:
ray[0].x_at_y(-1)

1.1111111111111112

In [9]:
start = vtem.RayNode((0., 0.), name='start')
middle= vtem.RayNode((3, -11), name='middle')
end = vtem.RayNode((0., -10.), name = 'end')
ray = vtem.Ray(start, end)
ray+=middle
print(ray)
fig = plt.figure()
ax = fig.add_subplot()
ray.show(ax, '-r')

ValueError: Could not add Node RayNode(3, -11, name=middle) to Ray(RayNode(0.0, 0.0, name= (start)), RayNode(0.0, -10.0, name= (end))). It does not fit between RayNode(0.0, 0.0, name= (start)) and RayNode(0.0, -10.0, name= (end))

In [8]:
ray-=middle
print(ray)
fig = plt.figure()
ax = fig.add_subplot()
ray.show(ax, '-r')

Ray with segments:
(0.00, 0.00) -> (0.00, -10.00) (0.00 deg)
(0.00, 0.00) -> (0.00, -10.00) (0.00 deg)


In [10]:
start = vtem.RayNode((0., 0.), name='start')

angles = np.linspace(-90, 90, 10)#np.arange(-90, 95, 0.5)
fig = plt.figure()
ax = fig.add_subplot()
for angle in angles:
    end = vtem.RayNode((0, -0.1), name = 'end')
    try:
        ray = vtem.Ray(start, end, angle=angle,     name='{}'.format(angle))
        print(ray)
    except Exception as e:
        print(start)
        print(end)
        print(ray.dx())
        print(ray.dy())
        raise e

    ray.show(ax, 'r')

Ray "-90.0": (0.00, 0.00) -> (-inf, 0.00) (-90.00 deg)
Ray "-70.0": (0.00, 0.00) -> (-0.27, -0.10) (-70.00 deg)
Ray "-50.0": (0.00, 0.00) -> (-0.12, -0.10) (-50.00 deg)
Ray "-30.0": (0.00, 0.00) -> (-0.06, -0.10) (-30.00 deg)
Ray "-10.0": (0.00, 0.00) -> (-0.02, -0.10) (-10.00 deg)
Ray "10.0": (0.00, 0.00) -> (0.02, -0.10) (10.00 deg)
Ray "30.0": (0.00, 0.00) -> (0.06, -0.10) (30.00 deg)
Ray "50.0": (0.00, 0.00) -> (0.12, -0.10) (50.00 deg)
Ray "70.0": (0.00, 0.00) -> (0.27, -0.10) (70.00 deg)
Ray "90.0": (0.00, 0.00) -> (inf, 0.00) (90.00 deg)


In [16]:
np.arcsin(ray.dx() / ray.dy())

<ipython-input-16-764c3844c50f>:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(ray.dx() / ray.dy())


nan

In [13]:
from math import asin
#print(end)
asin(ray.dx())

ValueError: math domain error

In [ ]:
10/sqrt(2)

In [10]:
sin(45*pi/180)


0.7071067811865476

In [9]:
-270%90


0

In [18]:
270%360

270

In [7]:
angles = np.arange(-360*2, 360*2, 1)
_angles = []
for angle in angles:
    a = angle%360
    if a > 180:
        a = a - 360
    _angles.append(a)
_angles = np.array(_angles)
#a = np.array([(ang%180)*(ang/abs(ang)) if ang%180for ang in angle])
#a[angle<0] = -a[angle<0]
fig = plt.figure()
ax = fig.add_subplot()
ax.plot(angles, _angles)

In [55]:
angles = np.arange(-360*2, 360*2, 1)
a = np.array([angle % 360 if angle%360 < 180 else angle%360 - 360 for angle in angles])
fig = plt.figure()
ax = fig.add_subplot()
ax.plot(angles, a, '.')


In [9]:
vtem.reduce_angle(-90) %90

0.0

In [4]:
from math import tan



In [12]:
angles = np.arange(-360, 360)
angles[angles%90==0] = 0
fig = plt.figure()
ax = fig.add_subplot()
ax.scatter(angles, [tan(vtem.reduce_angle(angle)*pi/180) if abs(vtem.reduce_angle(angle))<90 else -tan(vtem.reduce_angle(angle)*pi/180) for angle in angles])

In [33]:
270%90

0

In [36]:
180%90

0

In [38]:
90%180

90

In [3]:
np.sqrt(np.array([1, 2, 3]))




array([1.        , 1.41421356, 1.73205081])

In [4]:
end - start

array([array([0., 0.]), array([10., 10.])], dtype=object)

In [6]:
end.position - start.position

array([ 0., 10.])

In [3]:
end-start


end + start

array([ 10., -10.])

In [4]:
end-start

array([array([10., 10.]), array([-10., -10.])], dtype=object)

In [5]:
end-start


array([ 0.17455065, 10.        ])

In [13]:
l = list([vtem.RayNode(0, y) for y in np.random.random(4)])
l.sort(key=lambda x: x.y)
print(l)

[RayNode(0, 0.3213621828202542, name=), RayNode(0, 0.41906329538504594, name=), RayNode(0, 0.4844707109608146, name=), RayNode(0, 0.6710663260604717, name=)]


In [6]:
np.arctan(1)*180./np.pi



45.0

In [4]:
test = {'test': 'hei'}
print(test)
test.update({})
print(test)

{'test': 'hei'}
{'test': 'hei'}
